# Project:
#   adt 

# Purpose:
#   This Travis continuous integration file is use to compile and test JAVA
#   source files.

# Programming language
language: java

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

sudo: false
sddons:
  apt:
    packages:
      - oracle-java8-installer

# We will deploy the pdf file(s) back to a GitHub releases.
# deploy:
#   provider: releases
#   skip_cleanup: true
#   api_key:
#     secure:
#   file: _build/GettingStarted.pdf
#   on:
#     tags: true
#     branch: master
# repo: Traap/adt

# We will notify Allan Consulting's Slack channel tlc-article about Travis
# continuous integration status changes.
notifications:
  email: false
  slack: allanconsulting:V4c7i3ppz6IvrruMLUwFXcfE
